dist: bionic

language: java

jdk:
  - openjdk8
#  - openjdk11 # https://github.com/caeos/coner-timer/issues/4

script:
- ./mvnw verify -Dci=true

after_success:
- bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.m2
